import { Category } from './common.constant'

export interface Product {
    id: number
    name: string
    description: string
    notes: string
    image: string
    volume: number[] // volume will be in ml
    originalPrice: number
    salePrice: number
    category: Category
    isLatest?: boolean
    isBestSeller?: boolean
}

export const PRODUCT_LIST: Product[] = [
    {
        id: 1,
        name: 'Ombre leather',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/ombre-leather.png',
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 2,
        name: 'Boss',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/boss.png',
        originalPrice: 3500,
        salePrice: 2550,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 3,
        name: 'Althair',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/althair.png',
        originalPrice: 3550,
        salePrice: 2550,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 4,
        name: 'Kham-Rah',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/kham-rah.png',
        originalPrice: 3500,
        salePrice: 2350,
        isLatest: true,
        isBestSeller: true,
        category: Category.Unisex,
    },
    {
        id: 5,
        name: 'Cool Wave',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/cool-wave.png',
        originalPrice: 3650,
        salePrice: 3250,
        isLatest: true,
        isBestSeller: false,
        category: Category.Men,
    },
    {
        id: 6,
        name: 'Eroz',
        image: '/images/products/eroz.png',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 7,
        name: 'Floraa',
        image: '/images/products/floraa.png',
        description: 'Lactonic, woody, gourmand',
        notes: 'Arguably the longest lasting cardamom perfume',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Women,
    },
    {
        id: 8,
        name: 'Tam-Dao',
        image: '/images/products/tam-dao.png',
        description: 'Spicy, Woody, Sweet',
        notes: 'A sexy tobacco fragrance for men',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Unisex,
    },
    {
        id: 9,
        name: 'Canel 5',
        image: '/images/products/canel5.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Women,
    },
    {
        id: 10,
        name: 'Burry Femme',
        image: '/images/products/burry-femme.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Women,
    },
    {
        id: 11,
        name: 'Badee-al-oud',
        image: '/images/products/badee-al-oud.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Unisex,
    },
    {
        id: 12,
        name: 'Allura sport',
        image: '/images/products/allura-sport.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 13,
        name: 'Blue by Jinn',
        image: '/images/products/blue-by-jinn.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 14,
        name: 'Marshmallow',
        image: '/images/products/marshmallow.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Women,
    },
    {
        id: 15,
        name: 'Nine PM',
        image: '/images/products/nine-pm.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 16,
        name: 'Ombre Nomade',
        image: '/images/products/ombre-nomade.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 17,
        name: '212 Black',
        image: '/images/products/212-black.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 18,
        name: 'Imagination',
        image: '/images/products/imagination.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 19,
        name: 'Prada Paradox',
        image: '/images/products/prada-paradox.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Women,
    },
    {
        id: 20,
        name: 'Rebel 9',
        image: '/images/products/rebel9.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Unisex,
    },
    {
        id: 21,
        name: 'Sheek OUD',
        image: '/images/products/sheek-oud.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 22,
        name: 'OUD Malaki',
        image: '/images/products/oud-malaki.png',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
]
