import { Category } from './common.constant'

export interface Product {
    id: number
    name: string
    description: string
    notes: string
    image: string
    volume: number[] // volume will be in ml
    originalPrice: number
    salePrice: number
    category: Category
    isLatest?: boolean
    isBestSeller?: boolean
}

export const PRODUCT_LIST: Product[] = [
    {
        id: 1,
        name: 'Soul of Bali Extrait De Parfum For Unisex',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/p1.webp',
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: false,
        category: Category.Men,
    },
    {
        id: 2,
        name: 'Granada Eau De Parfum For Men',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/p2.webp',
        originalPrice: 3500,
        salePrice: 2550,
        isLatest: true,
        isBestSeller: false,
        category: Category.Men,
    },
    {
        id: 3,
        name: 'Seville Eau De Parfum For Men',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/p3.webp',
        originalPrice: 3550,
        salePrice: 2550,
        isLatest: true,
        isBestSeller: true,
        category: Category.Men,
    },
    {
        id: 4,
        name: 'Cadiz Eau De Parfum For Men',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/p4.webp',
        originalPrice: 3500,
        salePrice: 2350,
        isLatest: true,
        isBestSeller: true,
        category: Category.Women,
    },
    {
        id: 5,
        name: 'Odyssey BAHAMAS Eau De Parfum For Unisex',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        image: '/images/products/p5.webp',
        originalPrice: 3650,
        salePrice: 3250,
        isLatest: true,
        isBestSeller: false,
        category: Category.Women,
    },
    {
        id: 6,
        name: 'TSUNARA',
        image: '/images/products/p1.webp',
        description: 'Marine, Beastly, Clean, Woody',
        notes: "A potent freshie that's violent like a Tsunami",
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Women,
    },
    {
        id: 7,
        name: 'MILKY WAY',
        image: '/images/products/p2.webp',
        description: 'Lactonic, woody, gourmand',
        notes: 'Arguably the longest lasting cardamom perfume',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Unisex,
    },
    {
        id: 8,
        name: 'HAUTE TOBACCO',
        image: '/images/products/p3.webp',
        description: 'Spicy, Woody, Sweet',
        notes: 'A sexy tobacco fragrance for men',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Unisex,
    },
    {
        id: 9,
        name: 'TOBACCO VANILLA',
        image: '/images/products/p4.webp',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Unisex,
    },
    {
        id: 10,
        name: 'TOBACCO VANILLA',
        image: '/images/products/p5.webp',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Women,
    },
    {
        id: 11,
        name: 'TOBACCO VANILLA',
        image: '/images/products/p6.webp',
        description: 'Rich, Warm, Sophisticated',
        notes: 'An Opulent interplay of sweet & spicy notes',
        volume: [50],
        originalPrice: 8950,
        salePrice: 4990,
        isLatest: true,
        isBestSeller: true,
        category: Category.Women,
    },
]
