import type { Metadata } from 'next'
import { Montserrat, Rouge_Script } from 'next/font/google'
import './globals.css'
import Navbar from '@/component/navbar/Navbar.component'
import Footer from '@/component/footer/Footer.component'
import ScrollTop from '@/component/scrollTop/ScrollTop.component'
import React from 'react'

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
})

const rougeScript = Rouge_Script({
    variable: '--font-alex-brush',
    subsets: ['latin'],
    weight: ['400'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>): React.JSX.Element {
    return (
        <html lang="en">
            <body className={`${montserrat.variable} ${rougeScript.variable}`}>
                <Navbar />
                {children}
                <Footer />
                <ScrollTop />
            </body>
        </html>
    )
}
